kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-block-csi-operator
  labels:
    product: ibm-block-csi-driver
    csi: ibm
    app.kubernetes.io/name: ibm-block-csi-operator
    app.kubernetes.io/instance: ibm-block-csi-operator
    app.kubernetes.io/managed-by: ibm-block-csi-operator
subjects:
- kind: ServiceAccount
  name: ibm-block-csi-operator
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: ibm-block-csi-operator
  apiGroup: rbac.authorization.k8s.io
